import React, {FC, useState} from "react"
import EnterCode from "./EnterCode"
import EnterIdentifier from "./EnterIdentifier"

export const Login: FC = () => {
  // Identifier is the email or phone number entered by the user
  const [identifier, setIdentifier] = useState("")
  // TempUUID is the temporary UUID generated by the backend when the user enters their identifier
  const [tempUUID, setTempUUID] = useState("")

  return !tempUUID ? (
    <>
      <EnterIdentifier
        identifier={identifier}
        setIdentifier={setIdentifier}
        setTempUUID={setTempUUID}
      />
    </>
  ) : (
    <EnterCode tempUUID={tempUUID} identifier={identifier} />
  )
}
